export const stories = [
  {
    slug: "vn-surendran-journey",
    heroTitle: "A Life at Sea:",
    heroSubtitle: "VN Surendran's Journey Through Coastal and Foreign Shipping",
    title:
      "A Life at Sea: VN Surendran's Journey Through Coastal and Foreign Shipping",
    author: "VN Surendran, Chief Engineer",
    image: "/landing-page/stories/VN_Surendran.png",
    paragraphs: [
      "With nearly three decades at sea, VN Surendran has witnessed the Indian maritime industry evolve from traditional practices to today's increasingly regulated environment. Now 62 years old and sailing as a Chief Engineer, Surendran's career spans both foreign-going vessels and India's coastal (NCV) fleet.",
      "Holding a foreign-going certificate issued by Panama in the early 2000s, Surendran transitioned into coastal shipping over time. Reflecting on the shift, he acknowledges that while foreign-going vessels once carried more prestige, NCV vessels have improved significantly in recent years, especially in terms of standards, operations, and professional acceptance.",
      "\"I like working on NCV vessels,\" he says. \"Things are much better now compared to earlier years.\"",
      "Having spent close to 30 years in the shipping industry, Surendran has experienced the demands of shipboard life first-hand. One aspect he values deeply today is shore-side accessibility and support, particularly the ability to communicate issues quickly and receive timely assistance. Compared to earlier days, he notes that modern systems have improved maintenance planning and operational coordination.",
      "However, he believes there is still work to be done. From a policy perspective, Surendran feels that greater government-led education and awareness about shipping careers could encourage more young people to enter coastal shipping.",
      "\"If youngsters are properly educated about shipping and if rules and regulations are framed with seafarers' benefits in mind, more people will join,\" he explains.",
      "He also highlights the growing administrative burden in shipping today, particularly paperwork and regulatory compliance, drawing comparisons with European and US standards. While safety and compliance are essential, he feels that regulations often lean more towards owners than seafarers, and a better balance is needed.",
      "On the operational side, Surendran confirms that timely salary payments are critical to crew morale and stability, an area where consistency makes a noticeable difference to seafarers' confidence in their employers.",
      "When asked about his most memorable experience at sea, Surendran recalls a deeply personal and challenging Mumbai-Gulf voyage from when he was around 30 years old. Newly married at the time, with his wife pregnant back home, the ship was caught in a cyclone and left stranded at sea after the engine failed. For three days, the crew worked under intense pressure and uncertainty, unsure of what would happen next. When the engine finally came back to life and the vessel made it safely to shore, the relief was overwhelming. Decades later, the experience remains etched in his memory, not just for the technical challenge but for the emotional weight it carried.",
      "Originally from Kerala, Surendran continues to sail with the same sense of professionalism and commitment that has defined his career. His journey stands as a reminder that experience, adaptability, and dedication remain the backbone of the maritime industry, especially as coastal shipping continues to grow in importance.",
    ],
  },
  {
    slug: "tin-can-bridge-blue-economy",
    heroTitle: "My Maritime Journey:",
    heroSubtitle: "From Tin-Can Bridge to Blue Economy Resilience",
    title: "My Maritime Journey: From Tin-Can Bridge to Blue Economy Resilience",
    author: "Chukwuemeka Geoffery Chika, Marine Engineer",
    image: "/landing-page/stories/Chukwuemeka_Geoffery_Chika.png",
    paragraphs: [
      "As a young SIWES student in 2019, Chukwuemeka Geoffery Chika was on a mission to land his first internship. Walking across the bustling Tin-Can Bridge in Lagos, he spotted a promising office and boldly walked in. On his way back, he followed up with inquiries and secured a spot at an offshore supply vessel leasing company.",
      "What followed was an eye-opening experience alongside seasoned engineers. He absorbed invaluable lessons in vessel operations, from logistics to daily challenges, sparking his passion for the maritime world.",
      "His next chapter came during Industrial Training with Fleet Support Group (West). The seafarers' readiness for emergencies was military-grade, with swift drills executed with precision. He participated, learned, and honed skills that would define his path.",
      "Then COVID-19 hit like a rogue wave in 2020. Contracts evaporated, emergency protocols stretched training periods, and hands-on experience was cut short. Still, seafarers worldwide showed resilience, adapted, and helped shape new welfare and support systems powered by the internet's lifeline.",
      "Fast-forward to today, sustainability in the Blue Economy dominates. As a Nigerian seafarer, he has seen his country ramp up measures to hit 2030 goals, leading the charge in eco-friendly practices like reduced emissions and sustainable fishing.",
      "The maritime industry has evolved steeply from 2019 to 2026, with constant reforms building resilience and sustainability. His message is simple: never give up on your dreams, no matter the storms. The light within you will always guide the way.",
    ],
  },
  {
    slug: "sound-that-keeps-me-going",
    heroTitle: "The Sound",
    heroSubtitle: "That Keeps Me Going",
    title: "The Sound That Keeps Me Going",
    author: "By Rajat Khattri, 2/E (Marine Engineer)",
    image: "/landing-page/stories/Rajat_Khattri.png",
    paragraphs: [
      "Every day on board has its own rhythm. For most people, it is the sound of the sea. For Rajat Khattri, it is the low, steady hum of the main engine, a sound that reminds him that everything is working as it should.",
      "It is funny how something so mechanical can feel almost alive. Each morning, before the heat of the day builds up in the engine room, he does his first round, checking temperatures, pressures, fuel levels, and making sure every vibration feels normal.",
      "Over time, he has learned that machinery talks to you if you know how to listen. A small change in pitch or a slight difference in exhaust tone can be like a whisper from the heart of the ship.",
      "There are tough days: long hours, unexpected alarms, oily hands, and a constant layer of salt on everything. But what keeps him going is the routine, the discipline, and the quiet satisfaction of knowing that the ship sails smoothly because of what happens below deck.",
      "One of his favourite moments is when maintenance is complete, the machinery starts again, and everything runs flawlessly. That low hum returns, strong and steady, a sound that says, \"You did it right.\"",
      "Life at sea teaches patience, teamwork, and respect for the ocean, the machinery, and crewmates. Every day that ends with the engine running smoothly and the horizon calm is a reminder of the unseen heartbeat of the ship.",
    ],
  },
  {
    slug: "four-decades-at-sea",
    heroTitle: "Four Decades at Sea:",
    heroSubtitle: "What the Ocean Has Taught Me",
    title: "Four Decades at Sea: What the Ocean Has Taught Me",
    author: "Capt. Balajee Jayaraman",
    image: "/landing-page/stories/Balajee_Jayaraman.png",
    paragraphs: [
      "Capt. Balajee Jayaraman began sailing in 1982, straight from Jamshedpur, and has spent 43 years at sea, including 25 as a Master. Over these years, he has worked on nearly 90 ships, including tankers, bulk carriers, and container vessels.",
      "From 1982 to 1992, he remembers the best years of sailing: larger crews, longer periods in port, and time to explore. Communication was limited, so the focus stayed completely on work.",
      "Between 1992 and 2002, computers began to emerge, radio personnel were replaced, everything slowly digitized, and management took a more active role in ships. Crew sizes decreased while vessels became larger.",
      "From 2002 to 2012, the shift moved towards compliance. More regulations, reporting, and paperwork changed how people worked; precision and documentation became as important as seamanship itself.",
      "Since 2012, he has seen greater shore-side micromanagement and predicts more autonomy in the coming decade. He believes seafarers need transparency, security from owners and managers, timely relief, and continued support after they leave the vessel.",
      "A proud moment for him is that he has never faced a safety issue involving himself, his crew, or any vessel he has sailed on. His story is a reminder that seafarers move the industry and deserve better treatment, fair wages, and recognition.",
    ],
  },
  {
    slug: "tushar-sadashiv-25-years",
    heroTitle: "What 25 Years at Sea",
    heroSubtitle: "Taught Me",
    title: "What 25 Years at Sea Taught Me",
    author: "Tushar Sadashiv, Chief Engineer",
    image: "/landing-page/stories/Tushar_Sadashiv.png",
    paragraphs: [
      "Tushar Sadashiv has spent over 25 years at sea, a journey that has been both good and tough. This profession teaches quickly that one cannot wait for the right moment. The job must be done the right way, at the right time.",
      "Decision-making becomes second nature because lives, equipment, and time are always at stake. With experience and the right mentors, that ability sharpens, and continuous improvement becomes a daily mindset.",
      "In earlier days, there was more dedication from crew, but maritime training was often too theoretical with limited practical exposure. While systems have come a long way, he believes they should not change continuously without deep understanding.",
      "One incident he never forgets involved a mini bulk carrier with a serious technical issue. A faulty fuel tank valve led to fuel contamination and a full engine blackout. Investigation showed that a required 3-way cock was missing, and first-class approval was needed to rectify the design issue.",
      "He loves to read, especially Marathi literature, and believes there is always something to learn from others' stories. Another lesson he holds close is: do your homework before doing any work.",
      "Communication has changed drastically. Letters, radio communication, expensive satellite calls, limited text data, and now onboard Wi-Fi have all shaped how seafarers stay connected. Looking back, he feels satisfied and ready for opportunities where his experience can be useful.",
    ],
  },
  {
    slug: "between-waves-and-home",
    heroTitle: "Between the Waves",
    heroSubtitle: "and Home",
    title: "Between the Waves and Home",
    author: "Ambrish Kumar Mishra, 2nd Officer",
    image: "/landing-page/stories/Ambrish_Kumar_Mishra.png",
    paragraphs: [
      "Ambrish Kumar Mishra is from Prayagraj, Uttar Pradesh. He is married to Neetu Mishra and is a proud father of one daughter and one son.",
      "When onboard MT JILI, an oil and chemical tanker, he enjoys playing table tennis and chatting with the crew. When home, he tries to give maximum time to family and friends. He believes it is not only seafarers who sacrifice family time; families also sacrifice their presence.",
      "He loves his job onboard and gives his 100 percent to uphold the reputation of Indian seafarers and officers around the world. Seafarers reflect the image of their company and country, especially when working with mixed crews.",
      "The most memorable moment of his life was receiving the news that he had become a father. It was celebrated onboard, and the Captain even arranged a party for the occasion.",
      "He feels such moments are less common today. Interaction among crew has reduced, and many spend free time in cabins on the internet. Work pressure and changing habits have altered the atmosphere onboard.",
      "His dream is to command a ship under the flag of Nautilus Ship Management. His message to fellow mariners is to never overlook safety, onboard or ashore, and to save hard-earned money properly for the future and family.",
    ],
  },
  {
    slug: "pranet-practical-learning-at-sea",
    heroTitle: "Practical Learning at Sea:",
    heroSubtitle: "Pranet's Story",
    title: "Practical Learning at Sea: Pranet's Story",
    author: "Pranet, Deck Cadet",
    image: "/landing-page/stories/Pranet.png",
    paragraphs: [
      "As a trainee seafarer with four years of experience across four vessels aged between 15 and 22 years, Pranet's recent assignment on MT Yangtze was incredibly insightful.",
      "His typical work hours were 8 AM to 6 PM, though as a trainee the schedule varied based on work demands and navigational watches. He reported to the Chief Officer, who assigned daily tasks, with pending work carried over to the next day.",
      "Working on an older vessel like MT Yangtze gave him opportunities to develop practical skills such as hands-on problem-solving, teamwork, and collaboration with experienced crew.",
      "One highlight was completing a dry dock in China for almost 40 days. During this period, the entire vessel underwent maintenance, and he was deeply involved in inspecting ballast tank plates, overhauling valves, inspecting cargo tanks, preparing reports, and assisting senior officers.",
      "Although challenges included maintenance hurdles and limited resources, aging vessels offered a lot to learn from.",
      "His message to seafarers is that hands-on experience is the key to mastering your craft. New vessels may be easier, but older ships expose trainees to challenges that build stronger practical understanding.",
    ],
  },
  {
    slug: "mirza-riyasat-life-at-sea",
    heroTitle: "Mirza Riyasat",
    heroSubtitle: "on Life, Challenges, and Lessons at Sea",
    title: "Mirza Riyasat on Life, Challenges, and Lessons at Sea",
    author: "Mirza Riyasat, Chief Engineer",
    image: "/landing-page/stories/Mirza_Riyasat.png",
    paragraphs: [
      "Mirza Riyasat, Chief Engineer, shares his perspective from the 27-year-old passenger vessel Sivagangai, built in 1997 and operating between Nagapattinam, India, and KKS Port, Sri Lanka.",
      "Sivagangai began its current operations in 2024 under the management of Nautilus Shipping as part of a government project. For months, the vessel has navigated challenging waters and offered valuable lessons in managing older machinery.",
      "Being Chief Engineer on an old vessel is demanding. Every detail requires attention, and even small components must be meticulously maintained. Constant maintenance and vigilance over the engine are integral to the job.",
      "Despite the added challenges, his perspective remains positive: problems exist everywhere, but how you tackle them is what matters. A prompt response to any issue is key.",
      "His daily routine begins early, with immigration formalities, engine checklist completion, loading, passenger embarkation, and departure from Nagapattinam for the journey to KKS Port.",
      "For aspiring seafarers, he believes both new and old vessels offer different experiences. Older vessels provide frequent breakdowns and complexities that develop hands-on machinery knowledge, technical skills, and problem-solving ability.",
    ],
  },
  {
    slug: "guru-prasath-keep-trying",
    heroTitle: "Keep Trying:",
    heroSubtitle: "Guru Prasath's Message to Aspiring Seafarers",
    title: "Keep Trying: Guru Prasath's Message to Aspiring Seafarers",
    author: "Guru Prasath, Chief Officer",
    image: "/about-us/member/Sathish.webp",
    paragraphs: [
      "Guru Prasath has been a seafarer since March 2013, when he joined his first vessel as a trainee. He later became a Junior Officer and eventually an Officer.",
      "His inspiration came during school days, when he was inclined towards challenging fields like the Army, Navy, or Air Force. After attempting the NDA, a counselor suggested the merchant navy as a strong alternative.",
      "One memorable experience was staying awake for over 24 hours during intense work, an experience that made him realise how far seafarers can push themselves when the situation demands it.",
      "On 31 January 2025, during cargo operations in an Indian port, he received a call around 2 AM about smoke in cargo pumps. He immediately instructed the pump to be stopped and inspected the situation to prevent accidental release of toxic vapour.",
      "The team found a worn cargo pump bearing. Heavy rain and thunderstorms delayed repair work, but the crew worked through the night and completed the job. By sunrise, the machinery was set right, leaving satisfaction and smiles on their faces.",
      "His advice to aspiring seafarers is to keep trying, scale up skills, keep pushing, think positively, and remember that something will definitely turn.",
    ],
  },
];

export function getStoryBySlug(slug) {
  return stories.find((story) => story.slug === slug);
}
